CLASS LHC_ZZCIR_CIT_LIB_M_BM050050 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitLibMBm050050
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_LIB_M_BM050050 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
